name: Build

on:
    pull_request:
        paths:
            - '**.cc'
            - '**.h'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Library Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y libopus-dev
            - name: Install DPP
              run: |
                git clone https://github.com/brainboxdotcc/DPP
                cd DPP
                git switch --detach v10.1.3
                cmake -B ./build
                cmake --build ./build -j$(nproc)
                cd build
                sudo make install
            - name: Install mongocxx
              run: |
                curl -sOLf https://github.com/mongodb/mongo-cxx-driver/releases/download/r4.1.2/mongo-cxx-driver-r4.1.2.tar.gz
                tar -xzf mongo-cxx-driver-r4.1.2.tar.gz
                cd mongo-cxx-driver-r4.1.2/build
                cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20
                cmake --build . -j$(nproc)
                sudo cmake --build . --target install
            - name: Build Project
              run: make -j$(nproc)

