name: Commit Tasks

on:
    push:
        paths:
            - '**.cc'
            - '**.h'
    pull_request:
        paths:
            - '**.cc'
            - '**.h'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Library Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y zlib1g-dev libopus-dev
            - name: Install DPP
              run: |
                git clone https://github.com/brainboxdotcc/DPP
                cd DPP
                git switch --detach v10.1.3
                cmake -B ./build
                cmake --build ./build -j $(($(nproc) / 2))
                cd build
                sudo make install
            - name: Install mongocxx
              run: |
                curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r4.1.0/mongo-cxx-driver-r4.1.0.tar.gz
                tar -xzf mongo-cxx-driver-r4.1.0.tar.gz
                cd mongo-cxx-driver-r4.1.0/build
                cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20
                cmake --build .
                sudo cmake --build . --target install
            - name: Build
              run: make

